version: '2'
services:
  opa:
    image: openpolicyagent/opa:0.46.1-rootless
    ports:
      - 8181:8181
    command:
      - "run"
      - "--server"
      - "--log-format=json-pretty"
      - "--set=decision_logs.console=true"
      # - "--set=services.nginx.url=http://bundle_server"
      # - "--set=services.nginx.service=nginx"
      # - "--set=bundles.nginx.resrouce=bundles.tar.gz"
    # depends_on:
    #   - bundle_server
  # opal_server:
  #     image: permitio/opal-server:latest
  #     environment:
  #       #- OPAL_BROADCAST_URI=postgres://postgres:postgres@broadcast_channel:5432/postgres
  #       - UVICORN_NUM_WORKERS=1
  #       - OPAL_POLICY_REPO_URL=https://github.com/oualidktata/opa-fga
  #       - OPAL_POLICY_REPO_POLLING_INTERVAL=30
  #       - OPAL_DATA_CONFIG_SOURCES={"config":{"entries":[{"url":"http://localhost:7002/policy-data","topics":["policy_data"],"dst_path":"/static"}]}}
  #       - OPAL_LOG_FORMAT_INCLUDE_PID=true
  #     ports:
  #       - "7002:7002"
  #     #depends_on:
  #       #- broadcast_channel
  # opal_client:
  #   image: permitio/opal-client-standalone:latest
  #   environment:
  #     - OPAL_SERVER_URL=http://localhost:7002
  #     - OPAL_LOG_FORMAT_INCLUDE_PID=true
  #     - OPAL_INLINE_OPA_LOG_FORMAT=http
  #   ports:
  #     - "7000:7000"
  #     #- "8181:8181"
  #   depends_on:
  #     - opal_server
    #command: sh -c "./wait-for.sh opal_server:7002 --timeout=20 -- ./start.sh"

# https://docs.opal.ac/getting-started/quickstart/docker-compose-config/opal-server
# 
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always

  user_service:
    image: users-api:0.3.0
    build:
    - 
    ports:
    - 5000:5000
    environment:
    - OPA_ADR=http://opa:8181
    - POLICY_PATH=/v1/data/ads
    depends_on:
    - opa
    - redis
volumes:
  redis-data:
  # bundle_server:
  #   image: nginx:1.20.0-alpine
  #   ports:
  #   - 8888:80
  #   volumes:
  #   - ./bundles:/usr/share/nginx/html/bundles



