version: '4.3'
services:
  user-service:
    image: ${DOCKER_REGISTRY-}user-service
    container_name: user_service
    build:
      context: .
      dockerfile: ./Dockerfile
    #ports:
    #- 5000:80
    #- 5005:443
    environment:
    - OPA_ADR=http://opa:8181
    - POLICY_PATH=/v1/data/ads
    depends_on:
    #- opa
    - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:

     # bundle_server:
  #   image: nginx:1.20.0-alpine
  #   ports:
  #   - 8888:80
  #   volumes:
  #   - ./bundles:/usr/share/nginx/html/bundles



