version: '4.3'
services:
  user-service:
    image: ${DOCKER_REGISTRY-}user-service
    container_name: user_service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - 5000:80
    - 5001:443
    environment:
    - OPA_ADR=http://opa:8181
    - POLICY_PATH=/v1/data/ads
    depends_on:
    #- opa
    - redis-stack

  redis-stack:
    image: redis/redis-stack-server:latest
    container_name: redis-stack
    ports:
      - 6379:6379
    volumes:
      - redis-stack:/data
    restart: always

  redis-cache:
    image: redis:latest
    container_name: redis-cache
    ports:
      - 6380:6379
    volumes:
      - redis-cache:/data
    restart: always
volumes:
  redis-stack:
  redis-cache:

     # bundle_server:
  #   image: nginx:1.20.0-alpine
  #   ports:
  #   - 8888:80
  #   volumes:
  #   - ./bundles:/usr/share/nginx/html/bundles



